name: flappy_dash
description: "Flappy bird but in Flutter"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7"

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  flame: ^1.33.0
  flame_audio: ^2.11.11
  flame_bloc: ^1.12.18
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_comms: ^1.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.2
  hive_ce: ^2.15.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.7.0
  flame_lint: ^1.4.2
  flutter_gen_runner: ^5.11.0
  leancode_lint: ^19.0.0

flutter_gen:
  output: lib/resources/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/
    - assets/flags/
    - assets/images/
